#!/bin/bash
# rchat
# Simple rautafarmi chat client
# Licensed under GNU GPLv3.

# This will be used if something fails
RCHAT_DIE()
{
  printf "Died due to $EXITCODE" && exit 1
}

RCHAT_EXIT()
{
  rm -f /tmp/rchat-joined>/dev/null ; clear ; exit 0
}

RCHAT_INIT()
{
  DEFAULT_INSTANCE="https://donut.gq/rautafarmi"
  cat /tmp/rchat-instance > /dev/null || printf "$DEFAULT_INSTANCE" > /tmp/rchat-instance
  INSTANCE=$(cat /tmp/rchat-instance)
  LINECOUNT=40 # How many lines to print
  COLOR_01="$(printf '\033[0m')" # White
  COLOR_02="$(printf '\033[1;33m')" # Yellow
  COLOR_03="$(printf '\033[0;35m')" # Purple
  COLOR_04="$(printf '\033[0;36m')" # Blue
  COLOR_05="$(printf '\033[0;33m')" # Orange
  COLOR_06="$(printf '\033[0;31m')" # Red
  NAME="rchat" # rchat.. simple as that
  VERSION="0.2-19/04/2022-r2" # Version of rchat
  NICK="anon" # Default nickname is anon
  ls /tmp/rchat-nick>/dev/null && NICK=$(cat /tmp/rchat-nick)
  MODE=NORMAL
  RCHAT_URL="$INSTANCE/messages.txt"
  curl -so /tmp/rchat-msg $RCHAT_URL > /dev/null
  ls /tmp/rchat-joined>/dev/null || RCHAT_STARTER_HEADER
  . ~/.config/rchat/rchatrc>/dev/null
  case "$(echo $EDITOR)" in
  "") EDITOR=vim ;;
  esac
  RCHAT_GREP_MESSAGES
}

RCHAT_STARTER_HEADER()
{
  clear
  printf "$NAME $VERSION\n===============================================================================\n\n"
  printf "${COLOR_02}Last login: $(date '+%Y/%m/%d at %T')${COLOR_01}"
  printf "\n\nWelcome to $NAME $VERSION. $NAME is a rautafarmi chat client with Vim keybinds."
  printf "\n${COLOR_04}To join, type ':j'.\n"
  printf "\n${COLOR_02}rchat is licensed under the GNU GPLv3 license. Client written by speedie & potential contributors, rautafarmi is owned by donut.gq.\n${COLOR_01}"
  printf "\n${COLOR_03}To change instance, type ':set instance' and then enter your instance URL."
  printf "\n${COLOR_06}Type ':set instance default' to change it back.\n\n${COLOR_01}"
  read starter_command
  case "$starter_command" in
  ":q") RCHAT_EXIT ;;
  ":j") touch /tmp/rchat-joined && RCHAT_INIT ;;
  ":set instance") echo -n "Enter your instance: " ; read CUSTOM_INSTANCE ; printf "$CUSTOM_INSTANCE" > /tmp/rchat-instance && printf "\n${COLOR_06}000 - SYSTEM at $(date '+%Y/%m/%d %T:')\nSet instance to $CUSTOM_INSTANCE.${COLOR_01}" && sleep 3 && ${0} && RCHAT_EXIT ;;
  ":set instance default") echo $DEFAULT_INSTANCE > /tmp/rchat-instance && printf "${COLOR_06}\n000 - SYSTEM at $(date '+%Y/%m/%d %T:')\nSet instance to default.${COLOR_01}" && sleep 3 && ${0} && RCHAT_EXIT ;;
  esac
  ls /tmp/rchat-joined>/dev/null || ${0} && RCHAT_EXIT
}

RCHAT_HEADER()
{
  printf "$NAME $VERSION\n===============================================================================\n\n"
}

RCHAT_CAT_MESSAGES()
{
  RCHAT_FULL_MESSAGE_DATA=$(cat /tmp/rchat-msg | sed -n 1,$LINECOUNT\p | sed "s/<span style='color: #2c49c9;'>/${COLOR_03}/" | sed "s/<span style='color: #1c8757;'>/${COLOR_05}- /" | sed "s|</span>||" | sed "s|</span> <span style='color: #727272;'>| ${COLOR_06}at ${COLOR_04}|" | sed "s|</span>|${COLOR_01}:|" | sed "s|:<span style='color: #aa2cc9;'>|${COLOR_03}|" | sed "s|</span>|:${COLOR_03}|")

printf "$RCHAT_FULL_MESSAGE_DATA\n\n${COLOR_01}"
printf "===============================================================================\n"
printf "${COLOR_04}I: $INSTANCE L: $LINECOUNT/$(cat /tmp/rchat-msg | wc -l) LL: $(date '+%Y/%m/%d at %T')${COLOR_01}\n"
printf "===============================================================================\n"
}

RCHAT_GREP_MESSAGES()
{
  clear
  RCHAT_HEADER # Print the header/banner
  RCHAT_CAT_MESSAGES # Print the messages
  RCHAT_FOOTER # Print the footer/banner
  printf "$MODE \n" # Print the default mode
  RCHAT_CHECK_UPDATE
}

RCHAT_SEND_MESSAGE()
{
  curl -sX POST $INSTANCE/post.php -F "name=$NICK" -F "msg=$RCHAT_SEND_MESSAGE" > /dev/null
  ls /tmp/rchat-editor-message> /dev/null && curl -sX POST $INSTANCE/post.php -F "name=$NICK" -F "msg=$(cat /tmp/rchat-editor-message)" > /dev/null
  rm -f /tmp/rchat-editor-message>/dev/null
  clear
  ${0} && RCHAT_EXIT
}

RCHAT_INSERT()
{
  clear && RCHAT_HEADER && RCHAT_CAT_MESSAGES
  echo -n "$MODE > " && read RCHAT_SEND_MESSAGE
  RCHAT_SEND_MESSAGE ; ${0} && RCHAT_EXIT
}

RCHAT_CHECK_UPDATE()
{
  case "$(cat /tmp/rchat-msg)" in
  "$(curl -s $RCHAT_URL)") RCHAT_CHECK_MODE ;;
  esac
  ${0} && RCHAT_EXIT # Reset the script if there are new messages
}

RCHAT_GREP_MESSAGES()
{
  clear
  RCHAT_HEADER # Print the header/banner
  RCHAT_CAT_MESSAGES # Print the messages
  printf "$MODE " # Print the default mode
  RCHAT_CHECK_UPDATE
}

RCHAT_INSERT()
{
  clear && RCHAT_HEADER && RCHAT_CAT_MESSAGES
  echo -n "$MODE > " && read RCHAT_SEND_MESSAGE
  RCHAT_SEND_MESSAGE ; ${0} && RCHAT_EXIT
}

RCHAT_CHECK_UPDATE()
{
  case "$(cat /tmp/rchat-msg)" in
  "$(curl -s $RCHAT_URL)") RCHAT_CHECK_MODE ;;
  esac
  ${0} && RCHAT_EXIT # Reset the script if there are new messages
}

RCHAT_CMD()
{
  clear && RCHAT_HEADER && RCHAT_CAT_MESSAGES
  echo -n ":" && read CMD
  case "$CMD" in
  "q") RCHAT_EXIT ;;
  "h") RCHAT_HELP | less ;;
  "r") ${0} && RCHAT_EXIT ;;
  "nick") read NICK && echo $NICK > /tmp/rchat-nick && ${0} && RCHAT_EXIT ;;
  "!") read RCHAT_SHELL_COMMAND && /bin/sh -c $RCHAT_SHELL_COMMAND && ${0} && RCHAT_EXIT ;;
  "changelog") RCHAT_CHANGELOG | less ;;
  "e") $EDITOR /tmp/rchat-editor-message && RCHAT_SEND_MESSAGE ;;
  esac
  ${0} && RCHAT_EXIT
}

RCHAT_HELP()
{
  printf "Rchat is a chat client with Vim keybinds. To enter text, press I at any time."
  printf "When you initially run it *from a terminal*, you need to join. You can do this by running :j rautafarmi\n"
  printf "\nOr you can run commands using by pressing : and then entering the command you want"
  printf "\nIf you wanna run a terminal command, type ':!'."
  printf "\nTo see the help screen, do ':h'."
  printf "\nTo change your nickname from '$NICK' to anything you want, ':nick'."
  printf "\nTo see the changelog, type ':changelog'."
  printf "\nTo type out a message in your defined $EDITOR, type ':e'."
}

RCHAT_CHANGELOG()
{
  printf "rchat 0.1-2022-04-18: Initial release"
  printf "\nrchat 0.1-2022-04-18-r2: Added color support, writing messages in \$EDITOR and config file"
  printf "\nrchat 0.2-2022-04-19: Added custom instance support and fixed sysop garbage being printed when it shouldn't. Also performed other minor improvements."
  printf "\nrchat 0.2-2022-04-19-r2: Small aesthetic tweaks and defined \$EDITOR if it wasn't already."
}

RCHAT_CHECK_MODE()
{
  read -t 1 -n 1 MODE
  case "$MODE" in
  "i") MODE=INSERT && RCHAT_INSERT ;;
  "") MODE=NORMAL && RCHAT_CHECK_UPDATE ;;
  ":") RCHAT_CMD ;;
esac
${0} && RCHAT_EXIT
}

# Bottom
RCHAT_INIT
RCHAT_CHECK_UPDATE
