#!/bin/bash
# rchat
# Simple rautafarmi chat client
# Licensed under GNU GPLv3.

RCHAT_EXIT()
{
  rm -f /tmp/rchat-editor-message ; clear ; exit 0
}

RCHAT_LOGOUT()
{
  rm -f /tmp/rchat-joined /tmp/rchat-editor-message ; clear ; ${0} ; RCHAT_EXIT
}

RCHAT_INIT()
{
  DEFAULT_INSTANCE="https://donut.gq/rautafarmi"
  cat /tmp/rchat-instance > /dev/null || printf "$DEFAULT_INSTANCE" > /tmp/rchat-instance
  INSTANCE=$(cat /tmp/rchat-instance)
  REFRESH_TIMEOUT=3
  LINECOUNT=40 # How many lines to print
  COLOR_01="$(printf '\033[0m')" # White
  COLOR_02="$(printf '\033[0;33m')" # Yellow
  COLOR_03="$(printf '\033[0;35m')" # Purple
  COLOR_04="$(printf '\033[0;36m')" # Blue
  COLOR_05="$(printf '\033[0;33m')" # Orange
  COLOR_06="$(printf '\033[0;31m')" # Red
  NAME="rchat" # rchat.. simple as that
  VERSION="0.5-26/04/2022" # Version of rchat
  
  # Check what to set the nick to
  if [[ -f "/tmp/rchat-nick" ]]; then
		NICK=$(cat /tmp/rchat-nick)
  else
		NICK="anon"
  fi
  
  MODE=NORMAL
  RCHAT_URL="$INSTANCE/messages.txt"
  
  # Download all messages from the instance
  RCHAT_DOWNLOAD_MESSAGES &

  # Check if an existing session is active
  if [[ -f "/tmp/rchat-joined" ]]; then
		printf "Existing session exists, joining.."
  else
		RCHAT_STARTER_HEADER
  fi
 
  # Check if an editor is defined, if not set it to vim
  if [[ "$EDITOR" = "" ]]; then
		EDITOR=vim
  fi

  RCHAT_GREP_MESSAGES
}

RCHAT_DOWNLOAD_MESSAGES()
{
  sleep $REFRESH_TIMEOUT
  curl -so /tmp/rchat-msg "$RCHAT_URL" > /dev/null
}

RCHAT_STARTER_HEADER()
{
  clear
  printf "$NAME $VERSION\n===============================================================================\n\n"
  printf "${COLOR_02}Last login: $(date '+%Y/%m/%d at %T')${COLOR_01}"
  printf "\n\nWelcome to $NAME $VERSION. $NAME is a rautafarmi chat client with Vim keybinds."
  printf "\n${COLOR_04}To join, type ':j'.\n"
  printf "\n${COLOR_02}rchat is licensed under the GNU GPLv3 license. Client written by speedie & potential contributors, rautafarmi is owned by donut.gq.\n${COLOR_01}"
  printf "\n${COLOR_03}To change instance, type ':set instance' and then enter your instance URL."
  printf "\n${COLOR_06}Type ':set instance default' to change it back.${COLOR_01}"
  printf "\nType ':q' to quit.\n"
  read starter_command
  case "$starter_command" in
  ":q") RCHAT_EXIT ;;
  ":j") touch /tmp/rchat-joined && RCHAT_INIT ;;
  ":set instance") echo -n "Enter your instance: " ; read CUSTOM_INSTANCE ; printf "$CUSTOM_INSTANCE" > /tmp/rchat-instance && printf "\n${COLOR_06}000 - SYSTEM at $(date '+%Y/%m/%d %T:')\nSet instance to $CUSTOM_INSTANCE.${COLOR_01}" && sleep 3 && ${0} && RCHAT_EXIT ;;
  ":set instance default") echo $DEFAULT_INSTANCE > /tmp/rchat-instance && printf "${COLOR_06}\n000 - SYSTEM at $(date '+%Y/%m/%d %T:')\nSet instance to default.${COLOR_01}" && sleep 3 && ${0} && RCHAT_EXIT ;;
  esac
  . /tmp/rchat-settings
  if [[ -f "/tmp/rchat-joined" ]]; then
		printf "Joining"
  else
		${0} && RCHAT_EXIT
  fi
}

RCHAT_HEADER()
{
  printf "$NAME $VERSION\n===============================================================================\n\n"
}

RCHAT_CAT_MESSAGES()
{
  RCHAT_FULL_MESSAGE_DATA=$(cat /tmp/rchat-msg | sed -n 1,$LINECOUNT\p | sed "s/<span style='color: #2c49c9;'>/${COLOR_03}/" | sed "s/<span style='color: #1c8757;'>/${COLOR_05}- /" | sed "s|</span>||" | sed "s|</span> <span style='color: #727272;'>| ${COLOR_06}at ${COLOR_04}|" | sed "s|</span>|${COLOR_01}:|" | sed "s|:<span style='color: #aa2cc9;'>|${COLOR_03}|" | sed "s|</span>|:${COLOR_03}|" | sed "s|<span style='color: #789922;'>||")
printf "$RCHAT_FULL_MESSAGE_DATA\n\n${COLOR_01}"
printf "\n\n$INSTANCE $(date '+%Y/%m/%d/%T')\n===================================================\n$RCHAT_FULL_MESSAGE_DATA" >> /tmp/rchat-history
printf "===============================================================================\n"
printf "${COLOR_04}I: $INSTANCE L: $LINECOUNT/$(cat /tmp/rchat-msg | wc -l) LL: $(date '+%Y/%m/%d at %T')${COLOR_01}\n"
printf "===============================================================================\n"
}

RCHAT_GREP_MESSAGES()
{
  clear
  RCHAT_HEADER # Print the header/banner
  RCHAT_CAT_MESSAGES # Print the messages
  RCHAT_FOOTER # Print the footer/banner
  printf " $MODE \n" # Print the default mode
  RCHAT_CHECK_UPDATE
}

RCHAT_SEND_MESSAGE()
{
  case "$RCHAT_MESSAGE_TYPE" in
  "editor") curl -sX POST $INSTANCE/post.php -F "name=$NICK" -F "msg=$(cat /tmp/rchat-editor-message)" > /dev/null ;;
  "normal") curl -sX POST $INSTANCE/post.php -F "name=$NICK" -F "msg=$RCHAT_SEND_MESSAGE" > /dev/null ;;
  esac
  printf "${COLOR_06}\n000 - SYSTEM at $(date '+%Y/%m/%d %T:')\nMessage '$RCHAT_SEND_MESSAGE' sent. ${COLOR_01}" && sleep 0.5
  clear
  ${0} && RCHAT_EXIT
}

RCHAT_INSERT()
{
  clear && RCHAT_HEADER && RCHAT_CAT_MESSAGES
  echo -n "$MODE > " && read RCHAT_SEND_MESSAGE
  RCHAT_SEND_MESSAGE ; ${0} && RCHAT_EXIT
}

RCHAT_CHECK_UPDATE()
{
  case "$(cat /tmp/rchat-msg)" in
  "$(curl -s $RCHAT_URL)") RCHAT_CHECK_MODE ;;
  esac
  ${0} && RCHAT_EXIT # Reset the script if there are new messages
}

RCHAT_GREP_MESSAGES()
{
  clear
  RCHAT_HEADER # Print the header/banner
  RCHAT_CAT_MESSAGES # Print the messages
  printf " $MODE " # Print the default mode
  RCHAT_CHECK_UPDATE
}

RCHAT_INSERT()
{
  clear && RCHAT_HEADER && RCHAT_CAT_MESSAGES
  echo -n "$MODE > " && read RCHAT_SEND_MESSAGE && RCHAT_MESSAGE_TYPE=normal
  RCHAT_SEND_MESSAGE ; ${0} && RCHAT_EXIT
}

RCHAT_CHECK_UPDATE()
{
  case "$(cat /tmp/rchat-msg)" in
  "$(curl -s $RCHAT_URL)") RCHAT_CHECK_MODE ;;
  esac
  ${0} && RCHAT_EXIT # Reset the script if there are new messages
}

RCHAT_CMD()
{
  clear && RCHAT_HEADER && RCHAT_CAT_MESSAGES
  echo -n ":" && read CMD
  case "$CMD" in
  "q") RCHAT_EXIT ;;
  "leave") RCHAT_LOGOUT ;;
  "h") RCHAT_HELP | less ;;
  "r") ${0} && RCHAT_EXIT ;;
  "set nick") echo -n "Enter nick: " && read NICK && echo $NICK > /tmp/rchat-nick && ${0} && RCHAT_EXIT ;;
  "set refreshdelay") echo -n "How many seconds: " && read refreshdelay && printf "$REFRESHDELAY" >> /tmp/rchat-settings ;;
  "!") echo -n "What shell command should run? " && read RCHAT_SHELL_COMMAND && "/bin/sh -c" "$RCHAT_SHELL_COMMAND" && ${0} && RCHAT_EXIT ;;
  "history") less /tmp/rchat-history ; ${0} && RCHAT_EXIT ;;
  "history clear") rm /tmp/rchat-history ; ${0} && RCHAT_EXIT ;;
  "changelog") RCHAT_CHANGELOG | less ;;
  "news") RCHAT_NEWS | less ;;
  "instance") RCHAT_INSTANCE_LIST | less ;;
  "e") $EDITOR /tmp/rchat-editor-message && RCHAT_MESSAGE_TYPE=editor && RCHAT_SEND_MESSAGE ;;
  esac
  ${0} && RCHAT_EXIT
}

RCHAT_HELP()
{
  printf "rchat help | Use hjkl to read\n\n"
  printf "rchat is a chat client with Vim keybinds. To enter text, press I at any time.\n"
  printf "When you initially run it from a terminal, you need to join.\n"
  printf "Joining is done using a command. Commands in rchat are used similar to Vim. This means most commands start with ':'.\n" 
  printf "Below is a list of all commands.\n\n"
  printf "To join the set instance, type ':j'. *CAN ONLY BE DONE IF YOU AREN'T ALREADY IN AN INSTANCE*"
  printf "\n- To set an instance (Otherwise the default will be used), type ':set instance'. *CAN ONLY BE DONE IF YOU AREN'T ALREADY IN AN INSTANCE*"
  printf "\n- If you wanna run a terminal command, type ':!'."
  printf "\n- To see the help screen, do ':h'."
  printf "\n- To change your nickname from '$NICK' to anything you want, ':set nick'."
  printf "\n- To change how often messages are downloaded, ':set refreshdelay'. *PLEASE DO NOT ABUSE THIS*"
  printf "\n- To change colors, ':set color1', ':set color2', ':set color3', ':set color4', ':set color5', ':set color6'."
  printf "\n- To reset settings to default, 'do :settings reset'."
  printf "\n- To see the changelog, type ':changelog'."
  printf "\n- To type out a message in your defined $EDITOR, type ':e'."
  printf "\n- To see a list of popular instances, type ':instance'."
  printf "\n- To download and see news, type ':news'."
  printf "\n- To see a full list of all messages downloaded combined, type ':history'."
  printf "\n- To clear the saved history, type ':history clear'."
  printf "\n- To leave the instance, type ':leave'."
  printf "\n- To quit rchat (You'll stay logged in), type ':q'."
}

RCHAT_CHANGELOG()
{
  printf "rchat 0.1-2022-04-18: Initial release"
  printf "\nrchat 0.1-2022-04-18-r2: Added color support, writing messages in \$EDITOR and config file"
  printf "\nrchat 0.2-2022-04-19: Added custom instance support and fixed sysop garbage being printed when it shouldn't. Also performed other minor improvements."
  printf "\nrchat 0.2-2022-04-19-r2: Small aesthetic tweaks and defined \$EDITOR if it wasn't already."
  printf "\nrchat 0.3-2022-04-20: Removed more trash present in some instances, added :news and :instance commands and other small tweaks."
  printf "\nrchat 0.4-2022-04-24: Added :history, :history clear and other bug fixes."
  printf "\nrchat 0.5-2022-04-26: Added :set refreshdelay and other fixes."
}

RCHAT_NEWS()
{
  curl -so /tmp/rchat-news https://raw.githubusercontent.com/speediegamer/rchat/main/rchat-news  
  cat /tmp/rchat-news | less
  rm /tmp/rchat-news
}

RCHAT_INSTANCE_LIST()
{
  curl -so /tmp/rchat-instance-list https://raw.githubusercontent.com/speediegamer/rchat/main/rchat-instance-list
  cat /tmp/rchat-instance-list | less
  rm /tmp/rchat-instance-list
}

RCHAT_CHECK_MODE()
{
  read -t 1 -n 1 MODE
  case "$MODE" in
  "i") MODE=INSERT && RCHAT_INSERT ;;
  "") MODE=NORMAL && RCHAT_CHECK_UPDATE ;;
  ":") RCHAT_CMD ;;
esac
${0} && RCHAT_EXIT
}

# Bottom
RCHAT_INIT
RCHAT_CHECK_UPDATE
