#!/bin/bash
# rchat
# Simple rautafarmi chat client
# Licensed under GNU GPLv3.

# This will be used if something fails
RCHAT_DIE()
{
  printf "Died due to $EXITCODE" && exit 1
}

RCHAT_EXIT()
{
  rm /tmp/rchat-joined ; clear ; exit 0
}

RCHAT_INIT()
{
  LINECOUNT=40p # How many lines to print
  COLOR_01='\033[0m' # White
  COLOR_02='\033[1;33m' # Yellow
  COLOR_03='\033[0;35m' # Purple
  COLOR_04='\033[0;36m' # Blue
  COLOR_05='\033[0;33m' # Orange
  NAME="rchat" # rchat.. simple as that
  VERSION="0.1-18/04/2022" # Version of rchat
  NICK="anon" # Default nickname is anon
  ls /tmp/rchat-nick > /dev/null && NICK=$(cat /tmp/rchat-nick)
  MODE=NORMAL
  RCHAT_URL="https://donut.gq/rautafarmi/messages.txt"
  curl -so /tmp/rchat-msg $RCHAT_URL
  ls /tmp/rchat-joined || RCHAT_STARTER_HEADER
  RCHAT_GREP_MESSAGES
}

RCHAT_STARTER_HEADER()
{
  clear
  printf "$NAME $VERSION\n===============================================================================\n\n"
  printf "Welcome to $NAME $VERSION. $NAME is a rautafarmi chat client with Vim keybinds."
  printf "\nTo join, type ':j rautafarmi'.\n"
  printf "\nrchat is licensed under the GNU GPLv3 license. Client written by speedie & potential contributors, rautafarmi is owned by donut.gq.\n"
  read starter_command
  case "$starter_command" in
  ":q") RCHAT_EXIT ;;
  ":j rautafarmi") touch /tmp/rchat-joined && RCHAT_INIT ;;
  esac
  ls /tmp/rchat-joined || ${0} && RCHAT_EXIT
}

RCHAT_HEADER()
{
  printf "$NAME $VERSION\n===============================================================================\n\n"
}

RCHAT_CAT_MESSAGES()
{
  RCHAT_FULL_MESSAGE_DATA=$(cat /tmp/rchat-msg | sed -n 1,$LINECOUNT | sed "s/<span style='color: #2c49c9;'>//" | sed "s/<span style='color: #1c8757;'>/- /" | sed "s|</span>||" | sed "s|</span> <span style='color: #727272;'>| at |" | sed "s|</span>|:|")

printf "$RCHAT_FULL_MESSAGE_DATA\n\n"
printf "===============================================================================\n"
}

RCHAT_GREP_MESSAGES()
{
  clear
  RCHAT_HEADER # Print the header/banner
  RCHAT_CAT_MESSAGES # Print the messages
  RCHAT_FOOTER # Print the footer/banner
  printf "$MODE \n" # Print the default mode
  RCHAT_CHECK_UPDATE
}

RCHAT_SEND_MESSAGE()
{
  curl -sX POST https://donut.gq/rautafarmi/post.php -F "name=$NICK" -F "msg=$RCHAT_SEND_MESSAGE" > /dev/null
  ${0} && RCHAT_EXIT
}

RCHAT_INSERT()
{
  clear && RCHAT_HEADER && RCHAT_CAT_MESSAGES
  echo -n "$MODE > " && read RCHAT_SEND_MESSAGE
  RCHAT_SEND_MESSAGE ; ${0} && RCHAT_EXIT
}

RCHAT_CHECK_UPDATE()
{
  case "$(cat /tmp/rchat-msg)" in
  "$(curl -s $RCHAT_URL)") RCHAT_CHECK_MODE ;;
  esac
  ${0} && RCHAT_EXIT # Reset the script if there are new messages
}

RCHAT_GREP_MESSAGES()
{
  clear
  RCHAT_HEADER # Print the header/banner
  RCHAT_CAT_MESSAGES # Print the messages
  printf "$MODE " # Print the default mode
  RCHAT_CHECK_UPDATE
}

RCHAT_SEND_MESSAGE()
{
  curl -sX POST https://donut.gq/rautafarmi/post.php -F "name=$NICK" -F "msg=$RCHAT_SEND_MESSAGE" > /dev/null
  ${0} && RCHAT_EXIT
}

RCHAT_INSERT()
{
  clear && RCHAT_HEADER && RCHAT_CAT_MESSAGES
  echo -n "$MODE > " && read RCHAT_SEND_MESSAGE
  RCHAT_SEND_MESSAGE ; ${0} && RCHAT_EXIT
}

RCHAT_CHECK_UPDATE()
{
  case "$(cat /tmp/rchat-msg)" in
  "$(curl -s $RCHAT_URL)") RCHAT_CHECK_MODE ;;
  esac
  ${0} && RCHAT_EXIT # Reset the script if there are new messages
}

RCHAT_CMD()
{
  clear && RCHAT_HEADER && RCHAT_CAT_MESSAGES
  echo -n ":" && read CMD
  case "$CMD" in
  "q") RCHAT_EXIT ;;
  "h") RCHAT_HELP | less ;;
  "r") ${0} && RCHAT_EXIT ;;
  "nick") read NICK && echo $NICK > /tmp/rchat-nick && ${0} && RCHAT_EXIT ;;
  "!") read RCHAT_SHELL_COMMAND && /bin/sh -c $RCHAT_SHELL_COMMAND && ${0} && RCHAT_EXIT ;;
  esac
  ${0} && RCHAT_EXIT
}

RCHAT_HELP()
{
  printf "Rchat is a chat client with Vim keybinds. To enter text, press I at any time."
  printf "When you initially run it *from a terminal*, you need to join. You can do this by running :j rautafarmi\n"
  printf "\nOr you can run commands using by pressing : and then entering the command you want"
  printf "If you wanna run a terminal command, type ':!'."
  printf "To see the help screen, do ':h'."
  printf "To change your nickname from '$NICK' to anything you want, ':nick'."
}

RCHAT_CHECK_MODE()
{
  read -t 1 -n 1 MODE
  case "$MODE" in
  "i") MODE=INSERT && RCHAT_INSERT ;;
  "") MODE=NORMAL && RCHAT_CHECK_UPDATE ;;
  ":") RCHAT_CMD ;;
esac
${0} && RCHAT_EXIT
}

# Bottom
RCHAT_INIT
RCHAT_CHECK_UPDATE
